apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::242517964845:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1FTIORREM4RFN
      username: system:node:{{EC2PrivateDNSName}}
    - groups:  
      - system:masters
      rolearn: arn:aws:iam::242517964845:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-07T13:47:08Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1485"
  uid: 3069484f-1b7e-4755-a357-40d3c25df1f7
